### ISSUE TITLE
Issue of NodeOp aggregate_w

### ISSUE THREAD

**Issue by seungwonpark** [timctho/random-wired-nn-tensorflow#1]
Hi, thanks for implementing it in tensorflow and open-sourcing it!

I'm not familiar with tensorflow yet, but I think I've spotted a single mistake here.
At [custom_layer.py#L25](https://github.com/timctho/random-wired-nn-tensorflow/blob/master/src/model/custom_layer.py#L25), `self.aggregate_w` should pass through sigmoid layer to ensure they are positive. (ref: footnote 3 of paper)

**Comment by timctho** [comment]
Yes I forgot to add sigmoid, thanks!
